config/routes.rb
Rails.application.routes.draw do

  resources :lookups
  resources :tags
  resources :comments
  resources :posts

  root 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  devise_for :user, controllers: { sessions: "users/sessions" }

end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :set_lookup, only: [:show, :edit, :update, :destroy]

  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  # GET /lookups/1/edit
  def edit
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(lookup_params)

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render :show, status: :created, location: @lookup }
      else
        format.html { render :new }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lookups/1
  # PATCH/PUT /lookups/1.json
  def update
    respond_to do |format|
      if @lookup.update(lookup_params)
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { render :show, status: :ok, location: @lookup }
      else
        format.html { render :edit }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup.destroy
    respond_to do |format|
      format.html { redirect_to lookups_url, notice: 'Lookup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lookup
      @lookup = Lookup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lookup_params
      params.require(:lookup).permit(:name, :code, :type, :position)
    end
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_form.html.erb
<%= form_for(@lookup) do |f| %>
  <% if @lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% @lookup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lookups/edit.html.erb
<h1>Editing Lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lookups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Type</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lookups.each do |lookup| %>
      <tr>
        <td><%= lookup.name %></td>
        <td><%= lookup.code %></td>
        <td><%= lookup.type %></td>
        <td><%= lookup.position %></td>
        <td><%= link_to 'Show', lookup %></td>
        <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
        <td><%= link_to 'Destroy', lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lookup', new_lookup_path %>

app/views/lookups/new.html.erb
<h1>New Lookup</h1>

<%= render 'form' %>

<%= link_to 'Back', lookups_path %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lookup.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @lookup.code %>
</p>

<p>
  <strong>Type:</strong>
  <%= @lookup.type %>
</p>

<p>
  <strong>Position:</strong>
  <%= @lookup.position %>
</p>

<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>